# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test Pull Requests & Main Syncs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build and start test environment
        run: npm run start-coverage & wait-on http://localhost:3000
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: f005d141fc577a07c6e32bc71609eb6a52815e2a3c0ae4aa6d359ba447442cc0
        with:
          coverageCommand: npm run cypress:run
          coverageLocations: |
            ${{github.workspace}}/coverage/*.lcov:lcov
